- alias: Remind the kids 
  trigger:
    platform: state
    entity_id:
      - calendar.filippainloopse
      - calendar.lovisainloopse
    state: 'on'
  action: 
    - service: notify.ios_mickes_iphone
      data:
        title: 'Filippa!'
        message: 'Test'  
    - service: script.sonos_say
      data:
        sonos_entity: media_player.veranda
        volume: 0.2
        message: 'test'
        delay: '00:00:15'