- alias: Skafferåd på   
  trigger:
    - platform: state
      entity_id: binary_sensor.skafferadstrip_sensor
      from: 'off'
      to: 'on'    
  action:
    - service: switch.turn_on
      data:
        enitity_id: switch.skafferad_switch

- alias: Skafferåd av
  trigger:
    - platform: state
      entity_id: binary_sensor.skafferadstrip_sensor
      from: 'on'
      to: 'off'    
  action:
    - service: switch.turn_off
      data:
        enitity_id: switch.skafferad_switch

- alias: Trapperåd på
  trigger:
    - platform: state
      entity_id: binary_sensor.trapperadstrip_sensor
      from: 'off'
      to: 'on'    
  action:
    - service: switch.turn_on
      data:
        enitity_id: switch.trapperad_switch         

- alias: Trapperåd av
  trigger:
    - platform: state
      entity_id: binary_sensor.trapperadstrip_sensor
      from: 'on'
      to: 'off'    
  action:
    - service: switch.turn_off
      data:
        enitity_id: switch.skafferad_switch