automation:

  - alias: Turn on all the lights
    trigger:
      platform: time
      at: '06:30:00'
    action:
      service: light.turn_on
      entity_id: group.all_lights
  - alias: Turn off all the lights
    trigger:
      platform: time
      at: '23:45:00'
    action:
      service: light.turn_off
      entity_id: group.all_lights
      
  