homeassistant:
  customize:
    sensor.badrumsfukt_relative_humidity:
      friendly_name: Badrumsfukt

automation:
  - alias: Badrumfläkten på
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      above: 45
      below: 100
    action:
      - service: light.turn_on
        data: 
          enitity_id: light.badrumsflakt_level
          brightness: 200
  - alias: Badrumfläkten av
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      above: 0
      below: 45      
    action:
      - service: light.turn_off
        data: 
          enitity_id: light.badrumsflakt_level