homeassistant:
  customize:
    sensor.badrumsfukt_relative_humidity:
      friendly_name: Badrumsfukt

automation:

  - alias: Badrumsfläkten på
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      above: 60
    action:
      - service: homeassistant.turn_on
        data: 
          entity_id: light.badrumsflakt_level
          brightness: 200
      - service: notify.ios_mickes_iphone
        data:
          title: 'Fukt!'
          message: 'Startar Badrumsfläkten'

  - alias: Badrumsfläkten av
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity      
      below: 56
    action:
      - service: homeassistant.turn_off        
        entity_id: light.badrumsflakt_level
        

  - alias: Badrumsfläkten på on movement
    trigger:
      platform: state
      entity_id: binary_sensor.light.badrumsflakt_level
      to: 'on'
    action:
      service: homeassistant.turn_on
      data: 
          entity_id: light.badrumsflakt_level
          brightness: 120

  - alias: Badrumsfläkten av efter 10 minuter
    trigger:
      platform: state
      entity_id: binary_sensor.badrumsfukt_sensor
      to: 'off'
      for:
        minutes: 10
    action:
      service: homeassistant.turn_off
      entity_id: light.badrumsflakt_level