homeassistant:
  customize:
    sensor.badrumsfukt_relative_humidity:
      friendly_name: Badrumsfukt

automation:

  - alias: Badrumfläkten på
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      above: 45
    action:
      - service: homeassistant.turn_on
        data: 
          entity_id: light.badrumsflakt_level
          brightness: 200

  - alias: Badrumfläkten av
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity      
      below: 45
    action:
      - service: homeassistant.turn_off
        entity_id: light.badrumsflakt_level