homeassistant:
  customize:
    sensor.badrumsfukt_relative_humidity:
      friendly_name: Badrumsfukt

automation:
  - alias: Badrumfläkten på
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      value_template: '{{ sensor.badrumsfukt_relative_humidity - sensor.hallway_upstairs_humidity }}'
      above: 10
    action:
      - service: homeassistant.turn_on
        data: 
          entity_id: light.badrumsflakt_level
          brightness: 200
  - alias: Badrumfläkten av
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      value_template: '{{ sensor.badrumsfukt_relative_humidity - sensor.hallway_upstairs_humidity }}'
      below: 5      
    action:
      - service: light.turn_off
        data: 
          entity_id: light.badrumsflakt_level