homeassistant:
  customize:
    sensor.badrumsfukt_relative_humidity:
      friendly_name: Badrumsfukt

automation:

  - alias: Badrumsfl채kten p책
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity
      above: 65
    action:
      - service: homeassistant.turn_on
        data: 
          entity_id: light.badrumsflakt_level
          brightness: 200
      - service: notify.ios_mickes_iphone
        data:
          title: 'Fukt!'
          message: 'Startar Badrumsfl채kten'          

  - alias: Badrumsfl채kten av
    trigger:
      platform: numeric_state
      entity_id: sensor.badrumsfukt_relative_humidity      
      below: 60
    action:
      - service: homeassistant.turn_off
        entity_id: light.badrumsflakt_level