automation:
  - alias: Test
    trigger:
      platform: state
      entity_id: input_boolean.test_trigger      
      to: 'on'
    action:      
      - service: script.sonos_say
        data:
          sonos_entity: media_player.bathroom
          volume: 0.1
          message: 'Hej hopp Frü'
          delay: '00:00:02'
      - service: homeassistant.turn_on
        entity_id: switch.bikeroom_plug_switch
      - service: switch.turn_on
        entity_id: switch.bikeroom_plug_switch

  - alias: Bike Room light on on movement
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_humidity_sensor
      to: 'on'    
    action:
      - service: homeassistant.turn_on
        entity_id: switch.bikeroom_plug_switch

  - alias: Bike Room light off on movement
    trigger:
      platform: state
      entity_id: binary_sensor.bikeroom_sensor      
      to: 'off'
      for:
        minutes: 3
    action:
      - service: homeassistant.turn_off
        entity_id: switch.bikeroom_plug_switch
