automation:

  - alias: Bike Room light on on movement
    trigger:
      platform: state
      entity_id: binary_sensor.bikeroom_motion
      to: 'on'    
    action:
      - service: homeassistant.turn_on
        entity_id: switch.bikeroom_plug_switch

  - alias: Bike Room light off on movement
    trigger:
      platform: state
      entity_id: binary_sensor.bikeroom_motion      
      to: 'off'
      for:
        minutes: 3
    action:
      - service: homeassistant.turn_off
        entity_id: switch.bikeroom_plug_switch
