input_boolean:
  test_trigger:
    name: This is a test trigger
    initial: off
    icon: mdi:car

automation:
  - alias: Filippa till aktiviteter
    trigger:
      platform: state
      entity_id: input_boolean.test_trigger      
      to: 'on'
    action:      
      - service: tts.google_say
        entity_id: media_player.badrum
        data:
          message: 'May the Force be with you.'
      - service: notify.ios_mickes_iphone
        data:
          title: 'Hello!'
          message: 'Påminned Flipps'