input_boolean:
  test_trigger:
    name: This is a test trigger
    initial: off
    icon: mdi:car

automation:

  - alias: Test
    trigger:
      platform: state
      entity_id: input_boolean.test_trigger
      to: 'on'
    action: 
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.2
          message: 'Hej, nu testas det lite.'
          delay: '00:00:02'

  - alias: Filippa till aktiviteter
    trigger:
      platform: state
      entity_id: calendar.filippainloopse      
      to: 'on'
    action:      
      - service: script.sonos_say
        data:
          sonos_entity: media_player.bathroom
          volume: 0.2
          message: 'Aktivitet {{ message }}'
          delay: '00:00:02'

  - alias: 'Arrive pool notification'
    trigger:
      platform: zone
      event: enter
      zone: zone.pool
      entity_id: device_tracker.filippasiphone    
    action:
      - service: notify.ios_mickes_iphone
        data:
          title: 'Filippa!'
          message: 'Har kommit till simningen'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Filippa har kommit till Tibblebadet!'
          delay: '00:00:10'

  - alias: 'Leave pool notification'
    trigger:
      platform: zone
      event: leave
      zone: zone.pool
      entity_id: device_tracker.filippasiphone    
    action:
      - service: notify.ios_mickes_iphone
        data:
          title: 'Filippa!'
          message: 'Lämnar simningen'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Filippa lämnar Tibblebadet!'
          delay: '00:00:10'

  - alias: 'Arrive dance notification'
    trigger:
      platform: zone
      event: enter
      zone: zone.dance
      entity_id: device_tracker.filippasiphone    
    action:
      - service: notify.ios_mickes_iphone
        data:
          title: 'Filippa!'
          message: 'Har kommit till dansen'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Filippa har kommit till Laisings!'
          delay: '00:00:10'

  - alias: 'Leave dance notification'
    trigger:
      platform: zone
      event: leave
      zone: zone.dance
      entity_id: device_tracker.filippasiphone    
    action:
      - service: notify.ios_mickes_iphone
        data:
          title: 'Filippa!'
          message: 'Lämnar dansen'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Filippa lämnar Laisings!'
          delay: '00:00:10'

  - alias: 'Get the kids to school #1'
    trigger:
      platform: time
      at: '07:30:00'
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Det är nu en halvtimma innan skolan börjar! Nu måste ni borsta tänder och packa saker!'
          delay: '00:00:10'

  - alias: 'Get the kids to school #2'
    trigger:
      platform: time
      at: '07:40:00'
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Det är nu tjugo minuter till skolan börjar!'
          delay: '00:00:10'
          
  - alias: 'Get the kids to school #3'
    trigger:
      platform: time
      at: '07:50:00'
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.4
          message: 'Det är nu tio minuter till skolan börjar! Nu måste ni gå!'
          delay: '00:00:10'  