input_boolean:
  test_trigger:
    name: This is a test trigger
    initial: off
    icon: mdi:car

automation:
  - alias: Filippa till aktiviteter
    trigger:
      platform: state
      entity_id: input_boolean.test_trigger      
      to: 'on'
    action:      
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.2
          message: 'God kväll'
          delay: '00:00:02'      