input_boolean:
  test_trigger:
    name: This is a test trigger
    initial: off
    icon: mdi:car

input_boolean:
  test_trigger2:
    name: This is another test trigger
    initial: off
    icon: mdi:car    

automation:

  - alias: Filippa till aktiviteter
    trigger:
      platform: state
      entity_id: input_boolean.test_trigger
      state: 'on'
    action:      
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.test_trigger2