input_boolean:
  test_trigger:
    name: This is a test trigger
    initial: off
    icon: mdi:car

automation:
  - alias: Test
    trigger:
      platform: state
      entity_id: input_boolean.test_trigger      
      to: 'on'
    action:      
      - service: script.sonos_say
        data:
          sonos_entity: media_player.bathroom
          volume: 0.2
          message: 'God kväll'
          delay: '00:00:02'
  - alias: Filippa till aktiviteter
    trigger:
      platform: state
      entity_id: calendar.filippainloopse      
      to: 'on'
    action:      
      - service: script.sonos_say
        data:
          sonos_entity: media_player.bathroom
          volume: 0.2
          message: 'Aktivitet {{ message }}'
          delay: '00:00:02'
  - alias: 'Leave Home notification'
    trigger:
      platform: zone
      event: leave
      zone: zone.home
      entity_id: device_tracker.filippasiphone    
    action:
      - service: notify.ios_mickes_iphone
        data:
          title: 'Filippa!'
          message: 'Lämnar hemma'
  - alias: 'Get the kids to school'
    trigger:
      platform: time
      hours: 7
      minutes: 58
      seconds: 0    
    action:
      - service: script.sonos_say
        data:
          sonos_entity: media_player.kitchen
          volume: 0.3
          message: 'Det är nu tio minuter till skolan börjar'
          delay: '00:00:02'
     
