homeassistant:
  customize:
    media_player.kitchen:
      homebridge_visible: true
      friendly_name: Sonos Kitchen
    media_player.vardagsrum:
      homebridge_visible: true
      friendly_name: Sonos Living room
    media_player.veranda:
      homebridge_visible: true
      friendly_name: Sonos Veranda    

group:  
  media_players:
    view: yes
    name: Sonos    
    entities:
      - media_player.kithen
      - media_player.vardagsrum
      - media_player.veranda      

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
         language: 'sv'
     - delay: "{{ delay }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ sonos_entity }}"