homeassistant:
  customize:
    media_player.kitchen:
      homebridge_visible: true
      friendly_name: Sonos Kitchen
    media_player.vardagsrum:
      homebridge_visible: true
      friendly_name: Sonos Living room
    media_player.veranda:
      homebridge_visible: true
      friendly_name: Sonos Veranda

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: sonos.snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: sonos.unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_translate_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
         language: 'sv'
     - delay: "{{ delay }}"
     - service: sonos.restore
       data_template:
         entity_id: "{{ sonos_entity }}"