homeassistant:
  customize:
    binary_sensor.sensor:
      friendly_name: Skaffer책dstrip          

group:
  skafferad_lights:
    name: Skaffer책dlampan
    icon: mdi:spotlight-beam    
    entities:
      - switch.skafferad_switch

automation:

  - alias: Light Skaffer책d Door Activation
    trigger:
      platform: state
      entity_id: binary_sensor.sensor
      from: 'off'
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: group.skafferad_lights          

  - alias: Light Skaffer책d Door Restore
    trigger:
      platform: state
      entity_id: binary_sensor.sensor
      from: 'on'
      to: 'off'    
    action:
      - service: switch.turn_off
        entity_id: group.skafferad_lights