homeassistant:
  customize:
    binary_sensor.trapperadstrip_sensor:
      friendly_name: Trapper책dstrip          

group:
  trapperad_lights:
    name: Trapper책d lights
    icon: mdi:spotlight-beam
    entities:
      - switch.trapperad_switch

automation:

  - alias: Light Trapper책d Door Activation
    trigger:
      platform: state
      entity_id: binary_sensor.trapperadstrip_sensor
      from: 'off'
      to: 'on'
    action:
      - service: switch.turn_on
        entity_id: group.trapperad_lights          

  - alias: Light Trapper책d Door Restore
    trigger:
      platform: state
      entity_id: binary_sensor.trapperadstrip_sensor
      from: 'on'
      to: 'off'    
    action:
      - service: switch.turn_off
        entity_id: group.trapperad_lights